# Generated by Django 6.0 on 2026-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_quizmodel_passing_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
