# Generated by Django 5.2.11 on 2026-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_taskmodel_table_sql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['difficulty', 'created_at']},
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='expected_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='starter_code',
            field=models.TextField(blank=True, default='# Kodingizni shu yerga yozing\n'),
        ),
    ]
