# Generated by Django 5.2.11 on 2026-04-20 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coursemodel_is_free_alter_coursemodel_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', "Ko'p tanlovli"), ('code', 'Kod yozish')], default='mcq', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('code_template', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('topic', models.CharField(choices=[('basics', 'Asoslar'), ('strings', 'Satrlar'), ('lists', "Ro'yxatlar"), ('dicts', "Lug'atlar"), ('functions', 'Funksiyalar'), ('oop', 'OOP'), ('exceptions', 'Xatolar'), ('files', 'Fayllar'), ('modules', 'Modullar'), ('algorithms', 'Algoritmlar')], default='basics', max_length=30)),
                ('difficulty', models.IntegerField(default=2)),
                ('points', models.IntegerField(default=10)),
                ('explanation', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['topic', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='PlacementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('result_level', models.CharField(blank=True, default='', max_length=20)),
                ('topic_stats', models.JSONField(default=dict)),
                ('current_q_num', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=25)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('recommended_courses', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(default=0)),
                ('question_num', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.placementquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.placementsession')),
            ],
            options={
                'ordering': ['question_num'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('percentage', models.IntegerField(default=30)),
                ('valid_until', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_for_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_uses', to='core.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to='core.placementsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
